title = 'this is the configuration file of the plugin BeamTracker'

preset = 'preset_config'

do_init = true
detector = 'ImagingSource'
camera_name = 'DMK 42BUC03'

[references]
use_references = false
reference_1 = 'near-field'
reference_2 = 'far-field'

[camera_properties.exposure]
ExposureAuto = false
ExposureTime = 10

[camera_properties.gain]
GainAuto = false
Gain = 10