title = 'this is the configuration file of the plugin BeamTracker'

preset = 'preset_config'

do_init = true
detector = 'ImagingSource'
camera = 'DMK 42BUC03'

[camera_properties.exposure]
ExposureAuto = false
ExposureTime = 10

[camera_properties.gain]
GainAuto = false
Gain = 10